### ISSUE TITLE
Layered Drawing 2D

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#10]
I´ve encountered a problem trying rendering sprites over each other.
I render two sprites as follows
```
first->Position(Math::Vec3(0.0f, 0.0f, 10.0f));
second->Position2D(Math::Vec2(0.0f, 0.0f));
```
and I expect the first to be drawn above the second (changing position of first to ```Math::Vec3(0.0f, 0.0f, -10.0f);``` does not change anything). However, they are drawn in the order they were instantiated. Thus creating the second as first sprite and the first sprite as second yields the desired result.

The renderer is copy-pasted from example code
```
cherrysoda::Graphics::SetPointTextureSampling();
auto renderer = new cherrysoda::EverythingRenderer();
auto camera = renderer->GetCamera();
camera->Position(cherrysoda::Math::Vec3(0.0f, 0.0f, 200.0f));
renderer->SetEffect(cherrysoda::Graphics::GetEmbeddedEffect("sprite"));
renderer->KeepCameraCenterOrigin(false);
camera->UseOrthoProjection(true);
camera->CenterOrigin();
Add(renderer);
```

So my question is, how would you go on about rendering in layers, or is it something that needs to be implemented first?

(Also it seems that dynamically changing the Scale of a sprite is not supported. So can I assume that everything needs to be set up correctly on begin of a scene? And if so, how should zooming be accomplished?)

Thank you for your time!

**Comment by fountainment** [comment]
Sprite is something special, there is no corresponding drawcall for every single sprite, instead, it add data to SpriteBatch in order to get better rendering performance. And the z axis  data is actually ignored for sprite.

**Render order issue in this engine is mainly handled by Entity::Depth**, entities will be sorted everyframe based on its depth. Components in an entity are rendered by its adding order and are not sorted.

It's **not true** that things need to be set up on begin of a scene. Off course sprite is ok to be updated in  scene update. Something like this `sprite->Scale2D(Math::Vec2(scaleFloat));` should work.

When you encounter an issue that might be a bug, it will be better if you can give a minimal project for issue reproduction, otherwise I can't help much.

**Comment by CyberPlaton** [comment]
I understand now. Rendering layered with Entity::Depth works. Scaling in update works too, it was apparently some error from my side.
